apiVersion: v1
kind: ConfigMap
metadata:
  name: syslog-agent-config
  namespace: default
data:
  syslog-ng.conf: |
    @version: 3.26
    
    source s_dir { wildcard-file(
        base-dir("/var/log/containers")
        filename-pattern("random-logger*.log")
        max-files(1500)
        follow-freq(0.5)
        monitor-method(poll)
        log-fetch-limit(100)
        log-iw-size(15000)
        flags(no-parse)
        recursive(yes)
        multi-line-mode(indented)
    ); };
    
    destination d_syslog_tcp {
        network(
            "syslog-relay.default.svc.k8s.test.stratio.int"
            transport("tcp")
            port(7601)
        );
    };
      
    log {
        source(s_dir); destination(d_syslog_tcp);
    };