apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: syslog-agent
spec:
  selector:
    matchLabels:
      app: syslog-agent
  template:
    metadata:
      labels:
        app: syslog-agent
    spec:
      containers:
      - image: syslog-ng:test
        name: syslog-agent
        ports:
        - containerPort: 9577
        command: ["/bin/sh","-c"]
        args: ['/bin/syslog_ng_exporter --telemetry.address=":9577" --log.format="logger:stderr?appname=syslog-agent" --socket.path="/var/lib/syslog-ng/syslog-ng.ctl" & /usr/sbin/syslog-ng -F']
        volumeMounts:
        - mountPath: /var/log
          name: varlog
        - mountPath: /etc/syslog-ng
          name: syslog-ng-config
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - hostPath:
          path: /var/lib/docker/containers
          type: ""
        name: varlibdockercontainers
      - name: varlog
        hostPath:
          path: /var/log
      - configMap:
          defaultMode: 420
          name: syslog-agent-config
        name: syslog-ng-config
      securityContext:
        fsGroup: 0
        runAsGroup: 0
        runAsUser: 0