apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: core-prometheus-kube-prome-syslog-agent
  labels:
    app: core-prometheus-kube-prome-syslog-agent
  namespace: eos-metrics
spec:
  jobLabel: jobLabel
  selector:
    matchLabels:
      app: metrics
      app.kubernetes.io/instance: syslog-agent
  namespaceSelector:
    matchNames:
    - eos-logs
  endpoints:
  - port: metrics