apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syslog-relay-log-dest
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path