apiVersion: v1
kind: ConfigMap
metadata:
  name: syslog-relay-config
  namespace: default
data:
  syslog-ng.conf: |
    @version: 3.26
    
    source s_network {
      network(
        port(7601)
        transport("tcp")
        flags(no-multi-line, no-parse)
        max-connections(100)
      );
    };
    
    destination d_file {
        file("/var/result/test");
    };
      
    log {
        source(s_network); destination(d_file);
    };