apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: syslog-relay
spec:
  selector:
    matchLabels:
      app: syslog-relay
  replicas: 1
  serviceName: syslog-relay
  template:
    metadata:
      labels:
        app: syslog-relay
    spec:
      containers:
      - image: syslog-ng:test
        name: syslog-relay
        ports:
        - containerPort: 9577
          name: metrics
        - containerPort: 7601
          name: logs
        command: ["/bin/sh","-c"]
        args: ['/bin/syslog_ng_exporter --telemetry.address=":9577" --log.format="logger:stderr?appname=syslog-relay" --socket.path="/var/lib/syslog-ng/syslog-ng.ctl" & /usr/sbin/syslog-ng -F']
        volumeMounts:
        - mountPath: /var/log
          name: varlog
        - mountPath: /etc/syslog-ng
          name: syslog-ng-config
        - mountPath: /var/syslog-ng
          name: buffer
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - mountPath: /etc/certs
          name: certs
      volumes:
      - name: certs
        secret:
          defaultMode: 420
          items:
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key
          - key: ca.crt
            path: ca.crt
          secretName: syslog-relay-cert-tls
      - hostPath:
          path: /var/lib/docker/containers
          type: ""
        name: varlibdockercontainers
      - name: varlog
        hostPath:
          path: /var/log
      - name: buffer
        persistentVolumeClaim:
          claimName: syslog-relay-buffer
      - configMap:
          defaultMode: 420
          name: syslog-relay-config
        name: syslog-ng-config
      securityContext:
        fsGroup: 0
        runAsGroup: 0
        runAsUser: 0
