apiVersion: v1
kind: Service
metadata:
  name: syslog-relay
  labels:
    app: metrics
    app.kubernetes.io/instance: syslog-relay
spec:
  ports:
  - name: metrics
    port: 9577
    protocol: TCP
    targetPort: 9577
  - name: logs
    port: 7601
    protocol: TCP
    targetPort: 7601
  selector:
    app: syslog-relay